title: Aaron Luu
logo: "/images/AaronLuu.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring software engineer looking for enhanced real-world experience. Has experience with Object-oriented programming, algorithms, and data structures and is eager to learn more through an internship.
  <br><br>
  <a href="https://www.linkedin.com/in/aaron-luu123">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-89YR903VR0 # your Google Analytics tracking ID here
